In [10]:
import numpy as np 
a=np.array([[3,2], [1,3]])
b=np.array([[2,2], [1,2]])

#multiplicar
print(np.dot(a,b))

#producto escalar
print(np.vdot(a,b))


c=np.arange(6).reshape((2,3))
d=np.arange(3)

#####producto interno
print(np.inner(c,d))

####matriz elevada a..
e=np.array([[3,2], [1,3]])
print(np.linalg.matrix_power(e, 2))
    #print(np.dot(e,e))
    
#Determinantes y vectores propios

m=np.diag([4,3,2,1])
print(np.linalg.eig(m))
print(np.linalg.det(m))

#resolver ecuacion
a=np.array([[3,2], [1,3]])
b=np.array([9,9])

x=np.linalg.solve(a,b)
print(x)



[[ 8 10]
 [ 5  8]]
17
[ 5 14]
[[11 12]
 [ 6 11]]
(array([4., 3., 2., 1.]), array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]]))
24.000000000000004
[1.28571429 2.57142857]
