In [2]:
import numpy as np
a=np.arange(10)


#Slicing-consultar varias pos arrays
print(a[0:9])
print(a[0:9:2])
print(a[9::-1])

b=np.array([[1,2,3,4],[6,7,8,9]], dtype=int)
print(b[1,0:4])

c=np.matrix([[1,2,3,4],[6,7,8,9]], dtype=int)
print(c[1,0:4])


#indexado booleano 
print(a>4)
print(a[a>4])

#recorrido
for v in a:
    print(v)

a = np.array([0,1,2,3,4,5,6,7,8,9])
print(a[0:8:3])

[0 1 2 3 4 5 6 7 8]
[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]
[6 7 8 9]
[[6 7 8 9]]
[False False False False False  True  True  True  True  True]
[5 6 7 8 9]
0
1
2
3
4
5
6
7
8
9
[0 3 6]
