In [6]:
import numpy as np
###Dimensiones de array 

a=np.array([[1,2,3],[4,5,6]])

a.reshape(2,3)
a.ravel()##lo pone en forma lineal

##Tipos de arrays

np.asarray([1,2,3,4], dtype=float)#convierte lista python en array
np.asfarray([1,2,3,4])#convierte lista python en array de floats

np.asarray_chkfinite(a)#comprueba que no haya ni nan ni infinitos

np.repeat(a=99,repeats=10)#genera un array de 10 posiciones lineales con valor 99

###union de arrays

a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2,3]])

print(np.concatenate((a,b),axis=0))#axis=0 es a nivel filas e =1 es a nivel columnas
#np.stack(a,b)#misma funcion que concatenate

###SEPARACION DE arrays
a=np.array([[1,2,3,4,5,6]])
#np.split(a, indices_or_sections=2)#divide el array en 2 secciones iguales

np.insert(a,4,[5,6])#inserta en el array a en la pos 4 los valores 5 y 6
print(a)
np.append()#no se le pasa num de posicion, inserta valores al final
np.delete()#funciona de la misma forma que insrt pero solo se le pasa num de pos

np.trim_zeros(a)#elimina todos los ceros del array 

np.unique(a)#deja el array solo con los valores unicos

[[1 2 3]
 [4 5 6]
 [1 2 3]]
[[1 2 3 4 5 6]]
