In [6]:
import numpy as np
array1=np.array([1,2,3,4,5,6], dtype='int')

array2=np.array([[1,2,3],[4,5,6]], ndmin=2)
                
array3=np.array([1,2,3], dtype='complex')


#np.zeros
#np.ones
#np.arange
#reshape
array0=np.zeros(10)
print(array0)

arrayTp=np.ones((5,2))
print(arrayTp)

arrayAr=np.arange(0,10)
print(arrayAr)

arrayAr.reshape((5,2))



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[0 1 2 3 4 5 6 7 8 9]


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])