In [1]:
import numpy as np 

print(np.eye(4))
print(np.eye(4, k=1))

np.identity(4)

np.full(shape=(4, 4), fill_value=99 )
np.full(shape=(4, 4), fill_value=[10,20,30,40] )

#creacion desde datos existentes

np.fromstring('1 2 3 4', sep=' ')

###Rangos numericos

np.linspace(start=1,stop=10, num=5) #devuelve 5 floats entre 1 y 10,,, si añadimos endpoint=true no coge el 10

np.logspace(start=2, stop=3.5, num=5)#devuelve 5 floats entre 2y 3.5. y hace 10** ese numero devuelto

###creacion de matrices

a=np.eye(4)
b=np.diag(a)

c=np.tri(N=5, M=5) #crea matriz con la diagonal y todos las posiciones de esta con valor 1. el resto 0


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
